### ISSUE TITLE
Better handling of network issues in worker

### ISSUE THREAD

**Issue by rgaudin** [kiwix/cardshop#87]
Current handling of network issues is not satisfying: 

* worker both polls data from API and post logs/statuses to the API.
* Network errors in POLLING is not marked as is and just ignored.
* Network errors in POSTING has integrated retry mechanism but without delays in between so it's unlikely that it is useful.
* Errors in POSTING results in failing the task but most probably without being able to report it to the API so from the server the task looks active while it has been abandoned on the worker.
* The existing timeout mechanism should be able to check that an assigned task to an idle worker has crashed and should time it out (because the regular timeout is very conservative in terms of delays).

### Logs from today's issue:

```
(whostenv) root@kiwix_worker:~# docker logs cardshop-worker-writer-B
INFO:base:Welcome to Cardshop writer worker:
INFO:utils.setting:Checking Settings...
INFO:base:Starting...
INFO:base:Working off https://api.cardshop.hotspot.kiwix.org/tasks/writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting task #5ced308d98c8bf137b7016f2 to scheduler.
INFO:base:Starting to work on 5ced308d98c8bf137b7016f2
INFO:base:updating task #5ced308d98c8bf137b7016f2 status to: waiting_for_card
INFO:base:periodic log upload..................
INFO:base:sending logs for task #5ced308d98c8bf137b7016f2.
INFO:base:Starting await_sdcard on slot B
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:periodic log upload..................
INFO:base:sending logs for task #5ced308d98c8bf137b7016f2.
INFO:base:SD-card inserted. Checking size
ERROR:utils:list index out of range
ERROR:base:Inserted SD-card is not large enough for image (0 bytes vs 114.44 GiB)
Traceback (most recent call last):
  File "worker/tasks/write.py", line 43, in run
    getattr(self, method)()
  File "worker/tasks/write.py", line 71, in await_sdcard
    img=humanfriendly.format_size(img_size, binary=True),
OSError: Inserted SD-card is not large enough for image (0 bytes vs 114.44 GiB)
INFO:base:updating task #5ced308d98c8bf137b7016f2 status to: failed_to_insert
INFO:base:job is not alive
ERROR:base:job crashed: Inserted SD-card is not large enough for image (0 bytes vs 114.44 GiB)
INFO:base:sending logs for task #5ced308d98c8bf137b7016f2.
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting task #5cee441398c8bf2683703364 to scheduler.
INFO:base:Starting to work on 5cee441398c8bf2683703364
INFO:base:updating task #5cee441398c8bf2683703364 status to: waiting_for_card
INFO:base:Starting await_sdcard on slot B
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:periodic log upload..................
INFO:base:sending logs for task #5cee441398c8bf2683703364.
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:periodic log upload..................
INFO:base:sending logs for task #5cee441398c8bf2683703364.
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:periodic log upload..................
INFO:base:sending logs for task #5cee441398c8bf2683703364.
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:Waiting for the SD-card to be inserted...
INFO:base:periodic log upload..................
INFO:base:sending logs for task #5cee441398c8bf2683703364.
INFO:base:periodic log upload..................
INFO:base:sending logs for task #5cee441398c8bf2683703364.
ERROR:base:string indices must be integers
Traceback (most recent call last):
  File "worker/tasks/write.py", line 43, in run
    getattr(self, method)()
  File "worker/tasks/write.py", line 59, in await_sdcard
    not self.canceled and get_task(self.task["_id"])[1]["status"] == "waiting_for_card"
TypeError: string indices must be integers
INFO:base:updating task #5cee441398c8bf2683703364 status to: failed_to_insert
INFO:base:job is not alive
ERROR:base:job crashed: string indices must be integers
INFO:base:sending logs for task #5cee441398c8bf2683703364.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f718dd88cc0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cardshop.hotspot.kiwix.org', port=443): Max retries exceeded with url: /tasks/writer/5cee441398c8bf2683703364?slot=B (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f718dd88cc0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker/utils/scheduler.py", line 102, in query_api
    params={"slot": Setting.usb_slot},
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cardshop.hotspot.kiwix.org', port=443): Max retries exceeded with url: /tasks/writer/5cee441398c8bf2683703364?slot=B (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f718dd88cc0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

Traceback (most recent call last):
  File "worker/tasks/write.py", line 43, in run
    getattr(self, method)()
  File "worker/tasks/write.py", line 59, in await_sdcard
    not self.canceled and get_task(self.task["_id"])[1]["status"] == "waiting_for_card"
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f718dda7f98>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cardshop.hotspot.kiwix.org', port=443): Max retries exceeded with url: /tasks/writer/5cee441398c8bf2683703364/status?slot=B (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f718dda7f98>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker/utils/scheduler.py", line 102, in query_api
    params={"slot": Setting.usb_slot},
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 146, in patch
    return request('patch', url, data=data, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cardshop.hotspot.kiwix.org', port=443): Max retries exceeded with url: /tasks/writer/5cee441398c8bf2683703364/status?slot=B (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f718dda7f98>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f718dd88198>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cardshop.hotspot.kiwix.org', port=443): Max retries exceeded with url: /tasks/writer/5cee441398c8bf2683703364/logs?slot=B (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f718dd88198>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker/utils/scheduler.py", line 102, in query_api
    params={"slot": Setting.usb_slot},
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cardshop.hotspot.kiwix.org', port=443): Max retries exceeded with url: /tasks/writer/5cee441398c8bf2683703364/logs?slot=B (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f718dd88198>: Failed to establish a new connection: [Errno 110] Connection timed out'))
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
INFO:base:requesting list of tasks for worker ch-kiwix-writer
```

**Comment by kelson42** [comment]
@rgaudin This ticket probably desserves an update (at least) considering new image-creator works really differently as before.
